version: "3.7"

services:
  build:
    image: xcompany/xbuild:devcontainer
    build:
      context: ../
      dockerfile: Dockerfile

  run:
    image: xcompany/xbuild:devcontainer
    depends_on:
      - build
    volumes:
      # Map the current Source Folder
      - ../:/workspace/
      - ../src/xcompany/xbuild/build/:/build/
      - ../src/xcompany/xbuild/rootfs/etc/xbuild/:/etc/xbuild/
      - ../src/xcompany/xbuild/rootfs/etc/cont-finish.d/:/etc/cont-finish.d/
      - ../src/xcompany/xbuild/rootfs/etc/cont-init.d/:/etc/cont-init.d/
      - ../src/xcompany/xbuild/rootfs/etc/fix-attrs.d/:/etc/fix-attrs.d/
      - ../src/xcompany/xbuild/rootfs/etc/services.d/:/etc/services.d/
      - ../src/xcompany/xbuild/rootfs/etc/socklog.rules/:/etc/socklog.rules/
      - ../src/xcompany/xbuild/rootfs/usr/local/bin/:/usr/local/bin/
      - ../src/xcompany/xbuild/rootfs/usr/local/include/:/usr/local/include/
      - ../src/xcompany/xbuild/rootfs/var/local/xbuild:/var/local/xbuild
      # Configure Git with the current local Settings
      - ~/.gitconfig:/root/.gitconfig
      # Persists Extensions and VSCode Server
      - vscode-server:/root/.vscode-server
    cap_add:
        - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity

volumes:
  vscode-server:
